module.exports.default = module.exports = {
  data:
      {
        'crawler_time': '2017-04-01 12:45:13',
        'applyNo': '301201704010005754',
        'credit_card_others': {
          'lstUserCardInfo': [
            {
              'earliest_billtime': 'NumberLong',
              'bank': '建设银行',
              'holdername': '赵攀',
              'user_id': '2721197246',
              'card_id': 'NumberInt',
            },
          ],
          'lstUserMonthCardRecordtypeInfo': [
            {
              'amount': 110.49,
              'holdername': '赵攀',
              'month': '201703',
              'user_id': '2721197246',
              'num': 'NumberInt',
              'name': '利息',
              'type': '1',
              'card_id': 'NumberInt',
            },
          ],
          'lstNbUserMonthInfo': [],
          'userAppsInfo': [
            {
              'app_where_cnt': 'NumberInt',
              'app_tou_cnt': 'NumberInt',
              'app_xn_cnt': 'NumberInt',
              'app_wz_cnt': 'NumberInt',
              'app_yin_cnt': 'NumberInt',
              'app_you_cnt': 'NumberInt',
              'app_dai_cnt': 'NumberInt',
              'app_location_cnt': 'NumberInt',
              'app_zi_cnt': 'NumberInt',
              'app_tb_cnt': 'NumberInt',
              'app_dw_cnt': 'NumberInt',
              'app_li_cnt': 'NumberInt',
              'app_jie_cnt': 'NumberInt',
              'app_fu_cnt': 'NumberInt',
              'app_qian_cnt': 'NumberInt',
              'app_rong_cnt': 'NumberInt',
              'app_xin_cnt': 'NumberInt',
              'app_bt_cnt': 'NumberInt',
              'app_total_cnt': 'NumberInt',
              'app_cai_cnt': 'NumberInt',
              'app_lc_cnt': 'NumberInt',
              'app_hua_cnt': 'NumberInt',
              'app_jin_cnt': 'NumberInt',
              'app_xing_cnt': 'NumberInt',
            },
          ],
          'lstUserInfo': [
            {
              'jail_break': '0',
              'have_photo': '1',
              'holdername': '赵攀',
              'user_id': '2721197246',
              'position_app_name': '',
              'user_Nonborrower_num': 'NumberInt',
              'root': '',
              'if_zhaoshang': 'NumberInt',
              'virtual_machine': '0',
              'if_simplified': 'NumberInt',
              'mail_nonborrower_num': 'NumberInt',
            },
          ],
          'lstNbUserMonthCardInfo': [],
          'userSmsInfo': [
            {
              'sms_fk_cnt': 'NumberInt',
              'sms_lc_cnt': 'NumberInt',
              'sms_zn_cnt': 'NumberInt',
              'sms_cs_cnt': 'NumberInt',
              'sms_cz_cnt': 'NumberInt',
              'sms_kz_cnt': 'NumberInt',
              'sms_total_cnt': 'NumberInt',
              'sms_hk_cnt': 'NumberInt',
              'sms_qk_cnt': 'NumberInt',
              'sms_qz_cnt': 'NumberInt',
              'sms_tz_cnt': 'NumberInt',
              'phone_contacts_cnt': 'NumberInt',
              'sms_dk_cnt': 'NumberInt',
              'sms_jk_cnt': 'NumberInt',
              'sms_yq_cnt': 'NumberInt',
            },
          ],
          'lstUserCardCashriskInfo': [
            {
              'tran_date': 'NumberLong',
              'amount': 99.8,
              'holdername': '赵攀',
              'month': '201604',
              'user_id': '2721197246',
              'num': 'NumberInt',
              'type': '2',
              'card_id': 'NumberInt',
            },
          ],
          'lstUserMonthCardInfo': [
            {
              'isonehandmail': 'NumberInt',
              'bigbill_amount': 0.0,
              'bill_num': 'NumberInt',
              'min_payment': 497.24,
              'new_charges': 6798.2,
              'statement_date': 'NumberLong',
              'mailip': '',
              'billfromemail': '',
              'credit_limit': 5000.0,
              'currency': 'CNY',
              'new_balance': 4972.43,
              'highbill_amount': 99.6,
              'bill_num_simplified': 'NumberInt',
              'overdue_amount': 0.0,
              'last_pay_amount': 5000.0,
              'new_charges_amount': 199.2,
              'last_current_balance': 3174.23,
              'cash_credit_limit': 2500.0,
              'card_id': 'NumberInt',
              'new_charges_num': 'NumberInt',
              'holdername': '赵攀',
              'month': '201702',
              'user_id': '2721197246',
              'payment_due_date': 'NumberLong',
              'adjustment': 0.0,
              'mailsubject': '',
              'highbill_time': 'NumberLong',
            },
          ],
          'lstUserMonthInfo': [
            {
              'cre_num': 'NumberInt',
              'holdername': '赵攀',
              'month': '201607',
              'user_id': '2721197246',
            },
          ],
          'userAppInfo': [
            {
              'holdername': '赵攀',
              'app_version': '7.5.5',
              'partner': '',
              'user_id': '2721197246',
              'loan_channel': 'KN',
              'client_model': 'iPhone 6 Plus',
              'udid': '454AC9E0-150B-4B2C-9F2F-A741B52EC493',
            },
          ],
        },
        'insert_time': 'NumberLong',
        'group': '301201704010005754',

      },
};