module.exports.default = module.exports = {
  data: {
    'insertTime': '2017-09-15 14:06:51',
    'thirdId': '2a4f82c4c5e86a6f939fd227239cedab',
    'datapi_insert_time': 'NumberLong',
    'applyNo': '301201709153410022',
    'credit_card_others': {
      'lstUserCardInfo': [
        {
          'earliest_billtime': '2016-08-25 00:00:00',
          'bank': '交通银行',
          'holdername': '赵攀',
          'user_id': '2721197246',
          'if_simplified': '',
          'card_id': 'NumberInt',
        },
      ],
      'lstUserMonthCardRecordtypeInfo': [
        {
          'amount': 'NumberInt',
          'holdername': '赵攀',
          'month': '201706',
          'user_id': '2721197246',
          'num': 'NumberInt',
          'name': '航空',
          'type': '1',
          'card_id': 'NumberInt',
        },
      ],
      'lstNbUserMonthInfo': [],
      'userAppsInfo': {
        'app_tou_cnt': 'NumberInt',
        'app_xn_cnt': 'NumberInt',
        'app_wz_cnt': 'NumberInt',
        'app_you_cnt': 'NumberInt',
        'app_location_cnt': 'NumberInt',
        'app_dw_cnt': 'NumberInt',
        'app_tb_cnt': 'NumberInt',
        'app_jie_cnt': 'NumberInt',
        'app_bt_cnt': 'NumberInt',
        'app_total_cnt': 'NumberInt',
        'app_cai_cnt': 'NumberInt',
        'app_lc_cnt': 'NumberInt',
        'app_jin_cnt': 'NumberInt',
        'app_xing_cnt': 'NumberInt',
        'app_where_cnt': 'NumberInt',
        'app_yin_cnt': 'NumberInt',
        'app_dai_cnt': 'NumberInt',
        'app_zi_cnt': 'NumberInt',
        'app_li_cnt': 'NumberInt',
        'app_fu_cnt': 'NumberInt',
        'holdername': '赵攀',
        'app_qian_cnt': 'NumberInt',
        'app_rong_cnt': 'NumberInt',
        'app_xin_cnt': 'NumberInt',
        'user_id': '2721197246',
        'app_hua_cnt': 'NumberInt',
      },
      'lstUserInfo': [
        {
          'have_photo': '1',
          'jail_break': '0',
          'user_nonborrower_num': 'NumberInt',
          'holdername': '赵攀',
          'position_app_name': '',
          'user_id': '2721197246',
          'root': '',
          'if_zhaoshang': 'NumberInt',
          'virtual_machine': '0',
          'if_simplified': 'NumberInt',
          'mail_nonborrower_num': 'NumberInt',
        },
      ],
      'lstNbUserMonthCardInfo': [],
      'userSmsInfo': {
        'sms_fk_cnt': 'NumberInt',
        'sms_lc_cnt': 'NumberInt',
        'sms_zn_cnt': 'NumberInt',
        'sms_cs_cnt': 'NumberInt',
        'sms_cz_cnt': 'NumberInt',
        'sms_kz_cnt': 'NumberInt',
        'sms_total_cnt': 'NumberInt',
        'sms_hk_cnt': 'NumberInt',
        'holdername': '赵攀',
        'user_id': '2721197246',
        'sms_qk_cnt': 'NumberInt',
        'sms_qz_cnt': 'NumberInt',
        'sms_tz_cnt': 'NumberInt',
        'phone_contacts_cnt': 'NumberInt',
        'sms_dk_cnt': 'NumberInt',
        'sms_jk_cnt': 'NumberInt',
        'sms_yq_cnt': 'NumberInt',
      },
      'lstUserCardCashriskInfo': [
        {
          'tran_date': '2016-11-10 00:00:00',
          'amount': 'NumberInt',
          'holdername': '赵攀',
          'month': '201611',
          'user_id': '2721197246',
          'num': 'NumberInt',
          'type': '0',
          'card_id': 'NumberInt',
        },
      ],
      'lstUserMonthCardInfo': [
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 699.26,
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2017-06-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 6992.64,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 6794.64,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201706',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-07-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 679.46,
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2017-05-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 6794.64,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 6727.64,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201705',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-06-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-05-03 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 686.48,
          'new_charges': 8514.24,
          'maildate': '',
          'statement_date': '2017-04-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 6727.64,
          'highbill_amount': 15.24,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 15.24,
          'last_current_balance': 6214.4,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201704',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-05-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-04-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 728.59,
          'new_charges': 119.06,
          'maildate': '',
          'statement_date': '2017-03-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 6214.4,
          'highbill_amount': 119.06,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 119.06,
          'last_current_balance': 6895.34,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201703',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-04-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-03-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 781.86,
          'new_charges': 5101.58,
          'maildate': '',
          'statement_date': '2017-02-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 6895.34,
          'highbill_amount': 81.58,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 102.58,
          'last_current_balance': 6793.76,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201702',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-03-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-02-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 723.7,
          'new_charges': 4235.25,
          'maildate': '',
          'statement_date': '2017-01-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 6793.76,
          'highbill_amount': 49.25,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 49.25,
          'last_current_balance': 3958.51,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201701',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-02-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-01-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 882.33,
          'new_charges': 106.07,
          'maildate': '',
          'statement_date': '2016-12-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 3958.51,
          'highbill_amount': 86.66,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 19.41,
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 86.66,
          'last_current_balance': 3852.44,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201612',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-01-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-12-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 388.13,
          'new_charges': 4023.21,
          'maildate': '',
          'statement_date': '2016-11-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 3852.44,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 24.21,
          'last_current_balance': 2329.23,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201611',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-12-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-11-03 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 754.62,
          'new_charges': 53.64,
          'maildate': '',
          'statement_date': '2016-10-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 2329.23,
          'highbill_amount': 36.12,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 17.52,
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 36.12,
          'last_current_balance': 2275.59,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201610',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-11-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-10-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 350.49,
          'new_charges': 1127.59,
          'maildate': '',
          'statement_date': '2016-09-25 00:00:00',
          'card_no': '62225206****9918',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 2275.59,
          'highbill_amount': 136.59,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 136.59,
          'last_current_balance': 'NumberInt',
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201609',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-10-19 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-09-25 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 498.7,
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2017-06-22 00:00:00',
          'card_no': '6259652*****5857',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 'NumberInt',
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 'NumberInt',
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201706',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-07-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 22684.22,
          'maildate': '',
          'statement_date': '2017-06-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': -428.21,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 85.22,
          'last_current_balance': -150.43,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201706',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-07-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-06-19 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2017-05-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': -150.43,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 4656.57,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201705',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-06-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 465.66,
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2017-04-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 4656.57,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 12000.21,
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 5107.78,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201704',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-05-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 1237.61,
          'new_charges': 135.35,
          'maildate': '',
          'statement_date': '2017-03-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 5107.78,
          'highbill_amount': 110.49,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 135.35,
          'last_current_balance': 4972.43,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201703',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-04-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-03-22 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 497.24,
          'new_charges': 6798.2,
          'maildate': '',
          'statement_date': '2017-02-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 4972.43,
          'highbill_amount': 99.6,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 199.2,
          'last_current_balance': 3174.23,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201702',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-03-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-02-05 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 361.59,
          'new_charges': 1074.97,
          'maildate': '',
          'statement_date': '2017-01-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 3174.23,
          'highbill_amount': 49.9,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 98.97,
          'last_current_balance': 4799.26,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201701',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-02-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-12-30 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 1122.71,
          'new_charges': 295.15,
          'maildate': '',
          'statement_date': '2016-12-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 4799.26,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 25.1,
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 183.05,
          'last_current_balance': 4504.11,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201612',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-01-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-11-30 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 501.98,
          'new_charges': 1055.3,
          'maildate': '',
          'statement_date': '2016-11-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 4504.11,
          'highbill_amount': 57.3,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 57.3,
          'last_current_balance': 4448.81,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201611',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-12-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-11-22 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 978.64,
          'new_charges': 276.45,
          'maildate': '',
          'statement_date': '2016-10-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 4448.81,
          'highbill_amount': 108.61,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 20.86,
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 255.59,
          'last_current_balance': 4172.36,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201610',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-11-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-10-22 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 417.24,
          'new_charges': 4558.5,
          'maildate': '',
          'statement_date': '2016-09-22 00:00:00',
          'card_no': '43674800****8296',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 4172.36,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 87.5,
          'new_charges_amount': 'NumberInt',
          'last_current_balance': -298.64,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201609',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-10-11 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2017-06-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 9949.78,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 10021.78,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201706',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-07-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-06-08 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 11451.45,
          'maildate': '',
          'statement_date': '2017-05-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 10021.78,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 11451.45,
          'last_current_balance': 10070.33,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201705',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-06-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-05-08 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 3429.59,
          'maildate': '',
          'statement_date': '2017-04-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 10070.33,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 3429.59,
          'last_current_balance': 10140.74,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201704',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-05-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-04-10 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 1178.37,
          'maildate': '',
          'statement_date': '2017-03-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 10140.74,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 1178.37,
          'last_current_balance': 10062.37,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201703',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-04-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-03-17 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 7035.53,
          'maildate': '',
          'statement_date': '2017-02-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 10062.37,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 7035.53,
          'last_current_balance': 8026.84,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201702',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-03-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-02-14 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 177.54,
          'maildate': '',
          'statement_date': '2017-01-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 8026.84,
          'highbill_amount': 133.29,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 177.54,
          'last_current_balance': 8849.3,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201701',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-02-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2017-01-20 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 221.07,
          'maildate': '',
          'statement_date': '2016-12-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 8849.3,
          'highbill_amount': 160.42,
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 50.65,
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 170.42,
          'last_current_balance': 10128.23,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201612',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2017-01-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-12-20 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 2139.94,
          'maildate': '',
          'statement_date': '2016-11-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 10128.23,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 2139.94,
          'last_current_balance': 9988.29,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201611',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-12-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-11-10 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 1187.92,
          'maildate': '',
          'statement_date': '2016-10-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 9988.29,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 44.05,
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 1143.87,
          'last_current_balance': 8800.37,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201610',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-11-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-09-21 00:00:00',
        },
        {
          'isonehandmail': '',
          'bigbill_amount': 'NumberInt',
          'bill_num': 'NumberInt',
          'min_payment': 'NumberInt',
          'new_charges': 'NumberInt',
          'maildate': '',
          'statement_date': '2016-09-20 00:00:00',
          'card_no': '62255613****8482',
          'mailip': '',
          'billfromemail': '',
          'credit_limit': 'NumberInt',
          'currency': 'CNY',
          'email_no': '',
          'new_balance': 8800.37,
          'highbill_amount': 'NumberInt',
          'bill_num_simplified': 'NumberInt',
          'overdue_amount': 'NumberInt',
          'last_pay_amount': 'NumberInt',
          'new_charges_amount': 'NumberInt',
          'last_current_balance': 112.37,
          'cash_credit_limit': 'NumberInt',
          'available_points': 'NumberInt',
          'card_id': 'NumberInt',
          'new_charges_num': 'NumberInt',
          'holdername': '赵攀',
          'month': '201609',
          'new_points': 'NumberInt',
          'user_id': '2721197246',
          'mailfirsttime': '',
          'payment_due_date': '2016-10-09 00:00:00',
          'adjustment': 'NumberInt',
          'mailsubject': '',
          'highbill_time': '2016-08-23 00:00:00',
        },
      ],
      'lstUserMonthInfo': [
        {
          'cre_num': '4',
          'holdername': '赵攀',
          'month': '201706',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201609',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201612',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201701',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201611',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201610',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201703',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201702',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201705',
          'user_id': '2721197246',
        },
        {
          'cre_num': '3',
          'holdername': '赵攀',
          'month': '201704',
          'user_id': '2721197246',
        },
      ],
      'userAppInfo': {
        'app_version': '7.7.5',
        'holdername': '赵攀',
        'partner': '',
        'loan_channel': 'KN',
        'user_id': '2721197246',
        'client_model': 'iPhone 6 Plus',
        'client_os': 'ios',
        'udid': '454AC9E0-150B-4B2C-9F2F-A741B52EC493',
      },
    },
    'id_num_biz': '',
    'group': '301201709153410022',
  },
};